# Generated by Django 4.2.21 on 2025-05-22 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='age_filter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_joined_users',
            field=models.ManyToManyField(blank=True, related_name='deposit_join_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_like_users',
            field=models.ManyToManyField(blank=True, related_name='deposit_like_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='gender_filter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='age_filter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='gender_filter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_joined_users',
            field=models.ManyToManyField(blank=True, related_name='saving_join_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_like_users',
            field=models.ManyToManyField(blank=True, related_name='saving_like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
